report_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ReportBundle:Default:index }

report_facturastour:
    pattern:  /facturasTour
    defaults: { _controller: ReportBundle:Reporte:facturasTour  }

report_listReserv:
    pattern:  /listReserv
    defaults: { _controller: ReportBundle:Reporte:listReserv  }
#... view report template
report_facturasTour_view:
    pattern:  /viewFacturasTour
    defaults: { _controller: ReportBundle:Reporte:viewFacturasTour  }

report_listReserv_view:
    pattern:  /viewListReserv
    defaults: { _controller: ReportBundle:Reporte:viewListReserv  }
    options:
        expose: true

report_facturastour_pdf:
    pattern:  /viewFacturasTour/pdf
    defaults: { _controller: ReportBundle:Reporte:pdfFacturasTour  }

report_listReserv_pdf:
    pattern:  /viewListReserv/pdf
    defaults: { _controller: ReportBundle:Reporte:pdfListReserv  }

report_options:
    pattern: /options/export
    defaults: { _controller: ReportBundle:Reporte:options }

report_options_dayseek:
    pattern: /options/dat
    defaults: { _controller: ReportBundle:Reporte:dateSeek }
    options:
        expose: true
report_options_book_house:
    pattern: /options/book/house
    defaults: { _controller: ReportBundle:Reporte:homeBook }
    options:
        expose: true
report_options_book_house_month:
    pattern: /options/book/month
    defaults: { _controller: ReportBundle:Reporte:homeBookMonth }
    options:
        expose: true
report_options_tour_house_month:
    pattern: /options/tour/month
    defaults: { _controller: ReportBundle:Reporte:facturasMonthTour }
    options:
        expose: true

report_custom_invoice:
    pattern: /invoice/custom/booking
    defaults: { _controller: ReportBundle:Reporte:customInvoice }
    options:
        expose: true
report_custom_invoice_pdf:
    pattern: /invoice/{id}/custom/booking/pdf
    defaults: { _controller: ReportBundle:Reporte:customInvoicePDF }
#report_custom_invoice_plane:
#    pattern: /invoice/custom/booking/plaintext
#    defaults: { _controller: ReportBundle:Reporte:customInvoicePlane }
#