report_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ReportBundle:Default:index }

report_facturastour:
    pattern:  /facturasTour
    defaults: { _controller: ReportBundle:Default:facturasTour  }

report_facturasHouse:
    pattern:  /facturasHouse
    defaults: { _controller: ReportBundle:Default:facturasHouse  }

report_listReserv:
    pattern:  /listReserv
    defaults: { _controller: ReportBundle:Default:listReserv  }

report_listSummer:
    pattern:  /listSummer
    defaults: { _controller: ReportBundle:Default:listSummer  }

report_facturastour_pdf:
    pattern:  /facturasTour/pdf
    defaults: { _controller: ReportBundle:Default:pdfFacturasTour  }

report_facturasHouse_pdf:
    pattern:  /facturasHouse/pdf
    defaults: { _controller: ReportBundle:Default:pdfFacturasHouse  }

report_listReserv_pdf:
    pattern:  /listReserv/pdf
    defaults: { _controller: ReportBundle:Default:pdfListReserv  }

report_listSummer_pdf:
    pattern:  /listSummer/pdf
    defaults: { _controller: ReportBundle:Default:pdfListSummer  }
