parameters:
#    report.example.class: Booking\ReportBundle\Example

services:
#    report.example:
#        class: %report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
