parameters:
#    report.example.class: Booking\ReportBundle\Example

services:
    reportbundle.manager.reportmanager:
        class: Booking\ReportBundle\Manager\ReportManager
        arguments: [ @doctrine.orm.entity_manager ]