nomenclador:
    resource: "@NomencladorBundle/Resources/config/routing.yml"
    prefix:   /nomencladores

report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /reportes

booking:
    resource: "@BookingBundle/Resources/config/routing.yml"
    prefix:   /booking

#FOS
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"