homepage:
    pattern: /
    defaults: { _controller: "BookingBundle:Casa:index" }

nomenclador:
    resource: "@NomencladorBundle/Resources/config/routing.yml"
    prefix:   /nomencladores

report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /reportes

booking:
    resource: "@BookingBundle/Resources/config/routing.yml"
    prefix:   /booking

#FOS ROUTING
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"