<?php

namespace Booking\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasaRepository extends EntityRepository
{
}
