agencia:
    pattern:  /
    defaults: { _controller: "NomencladorBundle:Agencia:index" }

agencia_show:
    pattern:  /{id}/show
    defaults: { _controller: "NomencladorBundle:Agencia:show" }

agencia_new:
    pattern:  /new
    defaults: { _controller: "NomencladorBundle:Agencia:new" }

agencia_create:
    pattern:  /create
    defaults: { _controller: "NomencladorBundle:Agencia:create" }
    requirements: { _method: post }

agencia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NomencladorBundle:Agencia:edit" }

agencia_update:
    pattern:  /{id}/update
    defaults: { _controller: "NomencladorBundle:Agencia:update" }
    requirements: { _method: post|put }

agencia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NomencladorBundle:Agencia:delete" }
    requirements: { _method: post|delete }
