
reservacion_index:
     pattern: /index
     defaults: { _controller: "BookingBundle:Reservacion:index" }

reservacion_crear:
    pattern: /crear
    defaults: { _controller: "BookingBundle:Reservacion:create"  }

reservacion_editar:
    pattern: /editar
    defaults: { _controller: "BookingBundle:Reservacion:editForm" }
    options:
        expose: true

reservacion_actualizar:
    pattern: /{id}/actuaizar
    defaults: { _controller: "BookingBundle:Reservacion:update" }

reservacion_cancelar:
    pattern: /cancelar
    defaults: { _controller: "BookingBundle:Reservacion:delete" }
    options:
        expose: true

reservacion_listar:
    pattern: /listar
    defaults: { _controller: "BookingBundle:Reservacion:listar" }
    options:
        expose: true

reservacion_mostrar:
    pattern: /mostrar
    defaults: { _controller: "BookingBundle:Reservacion:mostrar" }
    options:
        expose: true

reservacion_casas_disponibles:
    pattern: /casas_disponibles
    defaults: { _controller: "BookingBundle:Reservacion:casasDisponibles" }
    options:
        expose: true

reservacion_associate:
    pattern: /associate/activity
    defaults: { _controller: "BookingBundle:Reservacion:associateActivity" }
    options:
        expose: true

reservacion_activity_form:
    pattern: /activity/custom/form
    defaults: { _controller: "BookingBundle:Reservacion:serveActivityForm" }
    options:
       expose: true

## the yml style configuration data
# reservacion_index: página principal, te da el formulario de nuevo (form)
# reservacion_listar: el listado de reservaciones[agencia, cliente, check in, check out, precio, casa]
# reservacion_mostrar: todos los datos de una reservacion(me envias un id, y te devuelvo el objeto completo)
# reservacion_crear: hacia donde apunta el formulario de crear nueva reservacion
# reservacion_editar: aqui te envio el formulario editar, me tienes que enviar el id de la reservacion
# reservacion_actualizar: hacia donde apunta el submit de los datos del formulario editar
# reservacion_cancelar: se cancela una reservacion, me envias el id
