parameters:
#    booking.example.class: Booking\BookingBundle\Example

services:
    booking.reservacionmanager:
        class: Booking\BookingBundle\Manager\ReservacionManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    booking_bookingbundle.form.agenciaselectortype:
        class: Booking\BookingBundle\Form\AgenciaSelectorType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: agenciaselector_type }

    booking_bookingbundle.form.clienteselectortype:
        class: Booking\BookingBundle\Form\ClienteSelectorType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: clienteselector_type }

    booking_bookingbundle.form.casaselectortype:
        class: Booking\BookingBundle\Form\CasaSelectorType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: casaselector_type }
    booking.apc.renderer:
        class: Booking\BookingBundle\Menu\Renderer\ApcRenderer
        arguments: [ %kernel.charset%, @booking.cache.adapter, 4000 ]
        tags:
            - { name: knp_menu.renderer, alias: apc }

    booking.cache.adapter:
        class: Desarrolla2\Cache\Adapter\Apc